### ISSUE TITLE
Can this software act as a transmitter?

### ISSUE THREAD

**Issue by fbdfbd3371** [Carbon225/raspberry-sbus#14]
Good day! Thanks for your efforts! I need to emulate a receiver on Linux and connect via a UART converter to the flight controller. I want to transmit control actions via SBUS, which will be synthesized on Linux. Am I correct in understanding that your software can act as both a receiver and a transmitter?

**Comment by Carbon225** [comment]
Yes, I recommend the passthrough example https://github.com/Carbon225/raspberry-sbus/blob/master/examples/passthrough.cpp

**Comment by fbdfbd3371** [comment]
Thanks a lot!
